name: Compatibility Check

on: push

jobs:
  fetch-versions:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install pip
      run: python -m pip install --upgrade pip

    - name: Fetch timm versions
      id: fetch-versions
      run: |
        VERSIONS=$(pip index versions timm | grep -oP '(?<=Available versions: ).*' | tr -d ' ' | tr -d '\n')
        echo "VERSIONS=$VERSIONS" >> $GITHUB_ENV

    - name: Set matrix for next job
      id: set-matrix
      run: |
        VERSIONS=$(echo $VERSIONS | jq -R -s -c 'split(",")')
        echo "::set-output name=matrix::{\"python-version\": [\"3.8\", \"3.9\", \"3.10\", \"3.11\"], \"timm-version\": $VERSIONS}"
  build:
    needs: fetch-versions
    runs-on: ubuntu-latest
    strategy:
      matrix: ${{fromJson(needs.fetch-versions.outputs.matrix)}}

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        if [ -f setup.py ]; then pip install .; fi

    - name: Install timm
      run: pip install timm==${{ matrix.timm-version }}

    - name: Run tests
      run: |
        pytest tests/test_decoder.py
        pytest tests/test_encoder.py
      continue-on-error: true
